package org.usfirst.frc.team1736.robot;

public enum LEDPatterns {
	SOLID_RED, STRIPES_FWD, STRIPES_REV, TWINKLE, OFF, PULSE_RED, VOLUME_CTRL1, RAINBOW, GRADIENT, TWINKLE_WEIRD, FIRE, SEVEN, RUSTY_AUTO_RED, ROYGBIV, TWINKLE_TOMS, GREEN, RED, BLUE, BRIGHT, SWAG, MURICA, CASS
}
